
FROM ghcr.io/existingperson08/arch-base:latest
RUN pacman -Syu --noconfirm

RUN rm -rf /lib/modules/*

RUN pacman -Syu --noconfirm linux-cachyos-deckify


#  :::::: finish :::::: 
RUN rm -rf /usr/etc
LABEL containers.bootc 1
RUN bootc container lint
