FROM ghcr.io/valerie-tar-gz/cachyos-bootc:latest


RUN pacman -R --noconfirm linux
RUN pacman -Sy --noconfirm linux-cachyos


RUN ln -s sysroot/ostree /ostree
LABEL containers.bootc 1
RUN bootc container lint
