FROM ghcr.io/existingperson08/arch-base:latest
#FROM ghcr.io/existingperson08/arch-base-cachy:latest

RUN mkdir -p /var/lib/pacman && pacman-db-upgrade || true
#RUN curl https://raw.githubusercontent.com/archlinux/archiso/refs/heads/master/configs/releng/pacman.conf > /etc/pacman.conf

RUN curl -O https://mirror.cachyos.org/cachyos-repo.tar.xz && \
    tar xf cachyos-repo.tar.xz && \
    cd cachyos-repo && \
    yes | ./cachyos-repo.sh

RUN pacman -Syu --needed --noconfirm

RUN rm -rf /lib/modules/*

RUN pacman -Scc --noconfirm || true
RUN rm -rf /var/lib/pacman/sync/*

RUN pacman -Syyu --needed --noconfirm curl

#RUN curl https://raw.githubusercontent.com/CachyOS/cachyos-calamares/refs/heads/cachyos-deckify-qt6/src/modules/netinstall/netinstall.yaml > /tmp/packages.txt
#RUN pacman -Sy --needed --noconfirm $(awk '/packages:/ {if($0~/\[/) {l=$0; sub(/.*\[/,"",l); sub(/\].*/,"",l); gsub(/["\x27]/,"",l); n=split(l,a,/,/); for(k=1;k<=n;k++) {gsub(/^[[:space:]]+|[[:space:]]+$/,"",a[k]); if(a[k]!="" && tolower(a[k])!~/firefox/) printf "%s ", a[k]}} else {f=1; i=match($0,/[^[:space:]]/)-1; next}} f {if(match($0,/[^[:space:]]/)-1<=i && $0!~/^[[:space:]]*$/) f=0; else if($0~/^[[:space:]]*-[[:space:]]/) {s=$0; sub(/^[[:space:]]*-[[:space:]]*/,"",s); sub(/#.*/,"",s); gsub(/["\x27]/,"",s); gsub(/^[[:space:]]+|[[:space:]]+$/,"",s); if(s!="" && tolower(s)!~/firefox/) printf "%s ", s}}' /tmp/packages.txt)

RUN curl -sSL https://raw.githubusercontent.com/CachyOS/CachyOS-Live-ISO/refs/heads/cachyos-deckify/archiso/packages_handheld.x86_64 > /tmp/packages.txt
#RUN yes | pacman -Sy --needed --noconfirm $( cat /tmp/packages.txt )

RUN pacman -Sy --noconfirm --overwrite="*" cachyos-deckify cachyos-deckify-headers

RUN while pacman -Sy --needed --noconfirm $(cat /tmp/packages.txt) 2>&1 | tee /tmp/pacman.log | grep -q "are in conflict"; do \
        conflicting_pkg=$(grep "are in conflict" /tmp/pacman.log | sed -E 's/.*and ([^ ]+) are in.*/\1/'); \
        echo "Removing conflicting package: $conflicting_pkg"; \
        pacman -Rdd --noconfirm "$conflicting_pkg" || break; \
    done

RUN pacman -R --noconfirm firefox

RUN pacman -Scc --noconfirm || true
RUN rm -rf /var/lib/pacman/sync/*

RUN mkdir -p /var/tmp
RUN printf "systemdsystemconfdir=/etc/systemd/system\nsystemdsystemunitdir=/usr/lib/systemd/system\n" | tee /usr/lib/dracut/dracut.conf.d/30-bootcrew-fix-bootc-module.conf && \
      printf 'hostonly=no\nadd_dracutmodules+=" ostree bootc "' | tee /usr/lib/dracut/dracut.conf.d/30-bootcrew-bootc-modules.conf && \
      sh -c 'export KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")" && \
      dracut --force --no-hostonly --reproducible --zstd --verbose --kver "$KERNEL_VERSION"  "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"'
#
#  :::::: finish :::::: 
RUN rm -rf /usr/etc
LABEL containers.bootc 1
RUN bootc container lint
